"""empty message

Revision ID: 14c5bd9cd46a
Revises: 
Create Date: 2025-01-29 12:50:06.492557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c5bd9cd46a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuraciones',
    sa.Column('id_config', sa.Integer(), nullable=False),
    sa.Column('tiempo_espera_vehiculo', sa.Time(), nullable=False),
    sa.Column('tiempo_total_en_recorrido', sa.Time(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fin', sa.Time(), nullable=False),
    sa.Column('cantidad_vehiculos_a_programar', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_config')
    )
    op.create_table('controles',
    sa.Column('id_control', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=8), nullable=False),
    sa.Column('latitud', sa.String(length=25), nullable=True),
    sa.Column('longitud', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id_control'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('departamentos',
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_departamento')
    )
    op.create_table('distritos',
    sa.Column('id_distrito', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_distrito')
    )
    op.create_table('fechas',
    sa.Column('id_fecha', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_fecha')
    )
    op.create_table('propietarios',
    sa.Column('id_propietario', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=50), nullable=False),
    sa.Column('apellidos', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('documento_identificacion', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id_propietario')
    )
    op.create_table('provincias',
    sa.Column('id_provincia', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_provincia')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('rol')
    )
    op.create_table('rutas',
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=8), nullable=False),
    sa.Column('inicio_vigencia', sa.DateTime(), nullable=False),
    sa.Column('fin_vigencia', sa.DateTime(), nullable=False),
    sa.Column('documento', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id_ruta'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=50), nullable=False),
    sa.Column('apellidos', sa.String(length=50), nullable=False),
    sa.Column('dni', sa.String(length=15), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('correo_electronico', sa.String(length=50), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('clave', sa.String(length=128), nullable=False),
    sa.Column('id_alternativo', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo_electronico'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('vehiculos',
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('flota', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=8), nullable=False),
    sa.Column('marca', sa.String(length=45), nullable=False),
    sa.Column('modelo', sa.String(length=45), nullable=False),
    sa.Column('fecha_fabricacion', sa.DateTime(), nullable=True),
    sa.Column('numero_asientos', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_vehiculo'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('disponibles_vehiculos',
    sa.Column('id_dv', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_final', sa.DateTime(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id_vehiculo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_dv')
    )
    op.create_table('programaciones',
    sa.Column('id_programacion', sa.Integer(), nullable=False),
    sa.Column('id_fecha', sa.Integer(), nullable=False),
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_fecha'], ['fechas.id_fecha'], ),
    sa.ForeignKeyConstraint(['id_ruta'], ['rutas.id_ruta'], ),
    sa.PrimaryKeyConstraint('id_programacion')
    )
    op.create_table('propietarios_vehiculos',
    sa.Column('id_pv', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_propietario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_propietario'], ['propietarios.id_propietario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id_vehiculo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pv')
    )
    op.create_table('secuencias_controles_rutas',
    sa.Column('id_scr', sa.Integer(), nullable=False),
    sa.Column('secuencia', sa.Integer(), nullable=False),
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.Column('id_control', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_control'], ['controles.id_control'], ),
    sa.ForeignKeyConstraint(['id_ruta'], ['rutas.id_ruta'], ),
    sa.PrimaryKeyConstraint('id_scr')
    )
    op.create_table('terminales',
    sa.Column('id_terminal', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=50), nullable=False),
    sa.Column('latitud', sa.String(length=25), nullable=False),
    sa.Column('longitud', sa.String(length=25), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('id_provincia', sa.Integer(), nullable=False),
    sa.Column('id_distrito', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamentos.id_departamento'], ),
    sa.ForeignKeyConstraint(['id_distrito'], ['distritos.id_distrito'], ),
    sa.ForeignKeyConstraint(['id_provincia'], ['provincias.id_provincia'], ),
    sa.PrimaryKeyConstraint('id_terminal')
    )
    op.create_table('usuarios_roles',
    sa.Column('id_ur', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_ur')
    )
    op.create_table('viajes',
    sa.Column('id_viaje', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.Column('id_fecha', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_fecha'], ['fechas.id_fecha'], ),
    sa.ForeignKeyConstraint(['id_ruta'], ['rutas.id_ruta'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id_vehiculo'], ),
    sa.PrimaryKeyConstraint('id_viaje')
    )
    op.create_table('asociados',
    sa.Column('id_asociado', sa.Integer(), nullable=False),
    sa.Column('id_pv', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pv'], ['propietarios_vehiculos.id_pv'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_asociado')
    )
    op.create_table('controles_tiempos',
    sa.Column('id_ct', sa.Integer(), nullable=False),
    sa.Column('tiempo', sa.Time(), nullable=False),
    sa.Column('id_control', sa.Integer(), nullable=False),
    sa.Column('id_viaje', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_control'], ['controles.id_control'], ),
    sa.ForeignKeyConstraint(['id_viaje'], ['viajes.id_viaje'], ),
    sa.PrimaryKeyConstraint('id_ct')
    )
    op.create_table('rutas_terminales',
    sa.Column('id_rt', sa.Integer(), nullable=False),
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.Column('id_terminal', sa.Integer(), nullable=False),
    sa.Column('id_terminal_2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ruta'], ['rutas.id_ruta'], ),
    sa.ForeignKeyConstraint(['id_terminal'], ['terminales.id_terminal'], ),
    sa.ForeignKeyConstraint(['id_terminal_2'], ['terminales.id_terminal'], ),
    sa.PrimaryKeyConstraint('id_rt')
    )
    op.create_table('vehiculos_programados',
    sa.Column('id_vp', sa.Integer(), nullable=False),
    sa.Column('tiempo', sa.Time(), nullable=True),
    sa.Column('vehiculo_en_espera', sa.Boolean(), nullable=True),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_programacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_programacion'], ['programaciones.id_programacion'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id_vehiculo'], ),
    sa.PrimaryKeyConstraint('id_vp')
    )
    op.create_table('planes_salidas',
    sa.Column('id_ps', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_vp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vp'], ['vehiculos_programados.id_vehiculo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_ps')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planes_salidas')
    op.drop_table('vehiculos_programados')
    op.drop_table('rutas_terminales')
    op.drop_table('controles_tiempos')
    op.drop_table('asociados')
    op.drop_table('viajes')
    op.drop_table('usuarios_roles')
    op.drop_table('terminales')
    op.drop_table('secuencias_controles_rutas')
    op.drop_table('propietarios_vehiculos')
    op.drop_table('programaciones')
    op.drop_table('disponibles_vehiculos')
    op.drop_table('vehiculos')
    op.drop_table('usuarios')
    op.drop_table('rutas')
    op.drop_table('roles')
    op.drop_table('provincias')
    op.drop_table('propietarios')
    op.drop_table('fechas')
    op.drop_table('distritos')
    op.drop_table('departamentos')
    op.drop_table('controles')
    op.drop_table('configuraciones')
    # ### end Alembic commands ###
