"""empty message

Revision ID: 3293505a8320
Revises:
Create Date: 2026-02-03 15:24:21.412497

"""
from alembic import op
import sqlalchemy as sa
import qhawariy
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '3293505a8320'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'configuraciones',
        sa.Column(
            'id_config',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),  # type: ignore
            nullable=False
        ),
        sa.Column('tiempo_espera_vehiculo', sa.Time(), nullable=False),
        sa.Column('tiempo_total_en_recorrido', sa.Time(), nullable=False),
        sa.Column('horario_inicio', sa.Time(), nullable=False),
        sa.Column('horario_fin', sa.Time(), nullable=False),
        sa.Column('cantidad_vehiculos_a_programar', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id_config'),
        schema='app'
    )
    op.create_table(
        'controles',
        sa.Column(
            'id_control',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('codigo', sa.String(length=8), nullable=False),
        sa.Column(
            'ubicacion',
            geoalchemy2.types.Geometry(
                geometry_type='POINT',
                srid=4326,
                dimension=2,
                from_text='ST_GeomFromEWKT',
                name='geometry',
                nullable=False
            ),
            nullable=False),
        sa.PrimaryKeyConstraint('id_control'),
        sa.UniqueConstraint('codigo'),
        schema='app'
    )
    # with op.batch_alter_table('controles', schema='app') as batch_op:
    #     batch_op.create_index(
    #         'idx_controles_ubicacion',
    #         ['ubicacion'],
    #         unique=False,
    #         postgresql_using='gist'
    #     )

    op.create_table(
        'departamentos',
        sa.Column(
            'id_departamento',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('nombre', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id_departamento'),
        schema='app'
    )
    op.create_table(
        'distritos',
        sa.Column(
            'id_distrito',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('nombre', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id_distrito'),
        schema='app'
    )
    op.create_table(
        'fechas',
        sa.Column(
            'id_fecha',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('fecha', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id_fecha'),
        schema='app'
    )
    op.create_table(
        'propietarios',
        sa.Column(
            'id_propietario',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('nombres', sa.String(length=50), nullable=False),
        sa.Column('apellidos', sa.String(length=50), nullable=False),
        sa.Column('telefono', sa.String(length=15), nullable=False),
        sa.Column('documento_identificacion', sa.String(length=15), nullable=False),
        sa.PrimaryKeyConstraint('id_propietario'),
        schema='app'
    )
    op.create_table(
        'provincias',
        sa.Column(
            'id_provincia',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('nombre', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id_provincia'),
        schema='app'
    )
    op.create_table(
        'roles',
        sa.Column(
            'id_rol',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('rol', sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint('id_rol'),
        sa.UniqueConstraint('rol'),
        schema='app'
    )
    op.create_table(
        'rutas',
        sa.Column(
            'id_ruta',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('codigo', sa.String(length=8), nullable=False),
        sa.Column('inicio_vigencia', sa.DateTime(), nullable=False),
        sa.Column('fin_vigencia', sa.DateTime(), nullable=False),
        sa.Column('documento', sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint('id_ruta'),
        sa.UniqueConstraint('codigo'),
        schema='app'
    )
    op.create_table(
        'usuarios',
        sa.Column(
            'id_usuario',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('nombres', sa.String(length=50), nullable=False),
        sa.Column('apellidos', sa.String(length=50), nullable=False),
        sa.Column('dni', sa.String(length=15), nullable=False),
        sa.Column('telefono', sa.String(length=15), nullable=False),
        sa.Column('correo_electronico', sa.String(length=50), nullable=False),
        sa.Column('fecha_registro', sa.DateTime(), nullable=True),
        sa.Column('clave', sa.String(length=128), nullable=False),
        sa.Column('id_alternativo', sa.String(length=6), nullable=False),
        sa.PrimaryKeyConstraint('id_usuario'),
        sa.UniqueConstraint('correo_electronico'),
        sa.UniqueConstraint('dni'),
        schema='app'
    )
    op.create_table(
        'vehiculos',
        sa.Column(
            'id_vehiculo',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('flota', sa.Integer(), nullable=False),
        sa.Column('placa', sa.String(length=8), nullable=False),
        sa.Column('marca', sa.String(length=45), nullable=False),
        sa.Column('modelo', sa.String(length=45), nullable=False),
        sa.Column('fecha_fabricacion', sa.DateTime(), nullable=True),
        sa.Column('numero_asientos', sa.Integer(), nullable=False),
        sa.Column('activo', sa.Boolean(), nullable=True),
        sa.Column('estado', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id_vehiculo'),
        sa.UniqueConstraint('placa'),
        schema='app'
    )
    op.create_table(
        'disponibles_vehiculos',
        sa.Column(
            'id_dv',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
        sa.Column('fecha_final', sa.DateTime(), nullable=False),
        sa.Column(
            'id_vehiculo',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['id_vehiculo'],
            ['app.vehiculos.id_vehiculo'],
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id_dv'),
        schema='app'
    )
    op.create_table(
        'notificaciones',
        sa.Column(
            'id_notificacion',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_usuario',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('mensaje', sa.String(length=255), nullable=False),
        sa.Column('esta_leida', sa.Boolean(), nullable=False),
        sa.Column('prioridad', sa.String(length=50), nullable=True),
        sa.Column('creado_en', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['id_usuario'], ['app.usuarios.id_usuario'], ),
        sa.PrimaryKeyConstraint('id_notificacion'),
        schema='app'
    )
    op.create_table(
        'programaciones',
        sa.Column(
            'id_programacion',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_fecha',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_ruta',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.ForeignKeyConstraint(['id_fecha'], ['app.fechas.id_fecha'], ),
        sa.ForeignKeyConstraint(['id_ruta'], ['app.rutas.id_ruta'], ),
        sa.PrimaryKeyConstraint('id_programacion'),
        schema='app'
    )
    op.create_table(
        'propietarios_vehiculos',
        sa.Column(
            'id_pv',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_vehiculo',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_propietario',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['id_propietario'],
            ['app.propietarios.id_propietario'],
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['id_vehiculo'],
            ['app.vehiculos.id_vehiculo'],
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id_pv'),
        schema='app'
    )
    op.create_table(
        'proximas_rutas',
        sa.Column(
            'id_pr',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_ruta',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_ruta2',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=True
        ),
        sa.ForeignKeyConstraint(['id_ruta'], ['app.rutas.id_ruta'], ),
        sa.ForeignKeyConstraint(['id_ruta2'], ['app.rutas.id_ruta'], ),
        sa.PrimaryKeyConstraint('id_pr'),
        schema='app'
    )
    op.create_table(
        'secuencias_controles_rutas',
        sa.Column(
            'id_scr',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('secuencia', sa.Integer(), nullable=False),
        sa.Column(
            'id_ruta',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_control',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.ForeignKeyConstraint(['id_control'], ['app.controles.id_control'], ),
        sa.ForeignKeyConstraint(['id_ruta'], ['app.rutas.id_ruta'], ),
        sa.PrimaryKeyConstraint('id_scr'),
        schema='app'
    )
    op.create_table(
        'terminales',
        sa.Column(
            'id_terminal',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('direccion', sa.String(length=50), nullable=False),
        sa.Column(
            'ubicacion',
            geoalchemy2.types.Geometry(
                geometry_type='POINT',
                srid=4326,
                dimension=2,
                from_text='ST_GeomFromEWKT',
                name='geometry',
                nullable=False
            ),
            nullable=False
        ),
        sa.Column(
            'id_departamento',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_provincia',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_distrito',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['id_departamento'],
            ['app.departamentos.id_departamento'],
        ),
        sa.ForeignKeyConstraint(['id_distrito'], ['app.distritos.id_distrito'], ),
        sa.ForeignKeyConstraint(['id_provincia'], ['app.provincias.id_provincia'], ),
        sa.PrimaryKeyConstraint('id_terminal'),
        schema='app'
    )
    # with op.batch_alter_table('terminales', schema='app') as batch_op:
    #     batch_op.create_index(
    #         'idx_terminales_ubicacion',
    #         ['ubicacion'],
    #         unique=False,
    #         postgresql_using='gist'
    #     )

    op.create_table(
        'usuarios_roles',
        sa.Column(
            'id_ur',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_usuario',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_rol',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.ForeignKeyConstraint(['id_rol'], ['app.roles.id_rol'], ),
        sa.ForeignKeyConstraint(['id_usuario'], ['app.usuarios.id_usuario'], ),
        sa.PrimaryKeyConstraint('id_ur'),
        schema='app'
    )
    op.create_table(
        'viajes',
        sa.Column(
            'id_viaje',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('orden', sa.Integer(), nullable=False),
        sa.Column(
            'id_vehiculo',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_ruta',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_fecha',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.ForeignKeyConstraint(['id_fecha'], ['app.fechas.id_fecha'], ),
        sa.ForeignKeyConstraint(['id_ruta'], ['app.rutas.id_ruta'], ),
        sa.ForeignKeyConstraint(['id_vehiculo'], ['app.vehiculos.id_vehiculo'], ),
        sa.PrimaryKeyConstraint('id_viaje'),
        schema='app'
    )
    op.create_table(
        'controles_tiempos',
        sa.Column(
            'id_ct',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('tiempo', sa.Time(), nullable=False),
        sa.Column(
            'id_control',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_viaje',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.ForeignKeyConstraint(['id_control'], ['app.controles.id_control'], ),
        sa.ForeignKeyConstraint(['id_viaje'], ['app.viajes.id_viaje'], ),
        sa.PrimaryKeyConstraint('id_ct'),
        schema='app'
    )
    op.create_table(
        'rutas_terminales',
        sa.Column(
            'id_rt',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_ruta',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_terminal',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_terminal_2',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.ForeignKeyConstraint(['id_ruta'], ['app.rutas.id_ruta'], ),
        sa.ForeignKeyConstraint(['id_terminal'], ['app.terminales.id_terminal'], ),
        sa.ForeignKeyConstraint(['id_terminal_2'], ['app.terminales.id_terminal'], ),
        sa.PrimaryKeyConstraint('id_rt'),
        schema='app'
    )
    op.create_table(
        'vehiculos_programados',
        sa.Column(
            'id_vp',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column('tiempo', sa.Time(), nullable=True),
        sa.Column('vehiculo_en_espera', sa.Boolean(), nullable=True),
        sa.Column(
            'id_vehiculo',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.Column(
            'id_programacion',
            qhawariy.utilities.uuid_endpoints.ShortUUID(length=36),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['id_programacion'],
            ['app.programaciones.id_programacion'],
        ),
        sa.ForeignKeyConstraint(['id_vehiculo'], ['app.vehiculos.id_vehiculo'], ),
        sa.PrimaryKeyConstraint('id_vp'),
        schema='app'
    )

    # op.create_table(
    #     'spatial_ref_sys',
    #     sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column(
    #         'auth_name',
    #         sa.VARCHAR(length=256),
    #         autoincrement=False,
    #         nullable=True
    #     ),
    #     sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    #     sa.Column(
    #         'srtext',
    #         sa.VARCHAR(length=2048),
    #         autoincrement=False,
    #         nullable=True
    #     ),
    #     sa.Column(
    #         'proj4text',
    #         sa.VARCHAR(length=2048),
    #         autoincrement=False,
    #         nullable=True
    #     ),
    #     sa.CheckConstraint(
    #         'srid > 0 AND srid <= 998999',
    #         name='spatial_ref_sys_srid_check'
    #     ),
    #     sa.PrimaryKeyConstraint(
    #         'srid',
    #         name='spatial_ref_sys_pkey'
    #     )
    # )
    # op.create_table(
    #     'topology',
    #     sa.Column(
    #         'id',
    #         sa.INTEGER(),
    #         server_default=sa.text("nextval('topology_id_seq'::regclass)"),
    #         autoincrement=True,
    #         nullable=False
    #     ),
    #     sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column(
    #         'precision',
    #         sa.DOUBLE_PRECISION(precision=53),
    #         autoincrement=False,
    #         nullable=False
    #     ),
    #     sa.Column(
    #         'hasz', sa.BOOLEAN(),
    #         server_default=sa.text('false'),
    #         autoincrement=False,
    #         nullable=False
    #     ),
    #     sa.Column(
    #         'useslargeids',
    #         sa.BOOLEAN(),
    #         server_default=sa.text('false'),
    #         autoincrement=False,
    #         nullable=False
    #     ),
    #     sa.PrimaryKeyConstraint('id', name='topology_pkey'),
    #     sa.UniqueConstraint('name', name='topology_name_key'),
    #     postgresql_ignore_search_path=False
    # )
    # op.create_table(
    #     'layer',
    #     sa.Column('topology_id', sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column('layer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column('schema_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column(
    #         'feature_column',
    #         sa.VARCHAR(),
    #         autoincrement=False,
    #         nullable=False
    #     ),
    #     sa.Column('feature_type', sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column(
    #         'level',
    #         sa.INTEGER(),
    #         server_default=sa.text('0'),
    #         autoincrement=False,
    #         nullable=False
    #     ),
    #     sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=True),
    #     sa.ForeignKeyConstraint(
    #         ['topology_id'],
    #         ['topology.id'],
    #         name='layer_topology_id_fkey'
    #     ),
    #     sa.PrimaryKeyConstraint('topology_id', 'layer_id', name='layer_pkey'),
    #     sa.UniqueConstraint(
    #         'schema_name',
    #         'table_name',
    #         'feature_column',
    #         name='layer_schema_name_table_name_feature_column_key'
    #     )
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('layer')
    op.drop_table('topology')
    op.drop_table('spatial_ref_sys')

    op.drop_table('vehiculos_programados', schema='app')
    op.drop_table('rutas_terminales', schema='app')
    op.drop_table('controles_tiempos', schema='app')
    op.drop_table('viajes', schema='app')
    op.drop_table('usuarios_roles', schema='app')
    with op.batch_alter_table('terminales', schema='app') as batch_op:
        batch_op.drop_index('idx_terminales_ubicacion', postgresql_using='gist')

    op.drop_table('terminales', schema='app')
    op.drop_table('secuencias_controles_rutas', schema='app')
    op.drop_table('proximas_rutas', schema='app')
    op.drop_table('propietarios_vehiculos', schema='app')
    op.drop_table('programaciones', schema='app')
    op.drop_table('notificaciones', schema='app')
    op.drop_table('disponibles_vehiculos', schema='app')
    op.drop_table('vehiculos', schema='app')
    op.drop_table('usuarios', schema='app')
    op.drop_table('rutas', schema='app')
    op.drop_table('roles', schema='app')
    op.drop_table('provincias', schema='app')
    op.drop_table('propietarios', schema='app')
    op.drop_table('fechas', schema='app')
    op.drop_table('distritos', schema='app')
    op.drop_table('departamentos', schema='app')
    with op.batch_alter_table('controles', schema='app') as batch_op:
        batch_op.drop_index('idx_controles_ubicacion', postgresql_using='gist')

    op.drop_table('controles', schema='app')
    op.drop_table('configuraciones', schema='app')
    # ### end Alembic commands ###
