from qhawariy.models import asociado
from qhawariy.models import plan_salida
from qhawariy.models import programacion
from qhawariy.models import propietario
from qhawariy.models import propietario_vehiculo
from qhawariy.models import rol
from qhawariy.models import ruta
from qhawariy.models import vehiculo_programado
from qhawariy.models import vehiculo
from qhawariy.models import viaje
from qhawariy.models import departamento
from qhawariy.models import distrito
from qhawariy.models import provincia
from qhawariy.models import fecha
from qhawariy.models import ruta_terminal
from qhawariy.models import terminal
from qhawariy.models import control
from qhawariy.models import control_tiempo
from qhawariy.models import configuracion
from qhawariy.models import secuencia_control_ruta
from qhawariy.models import proxima_ruta
